name: Run tests

on:
  push:
    branches:
    - test/actions

permissions:
  contents: write 

jobs:
  generate-docs:
    runs-on: macos-latest

    steps:
      - name: Trigger reusable workflow
        uses: feather-framework/feather-actions@0.0.19
        with:
          targets: "FeatherSpec"
          github_token: ${{ secrets.GITHUB_TOKEN }}