name: Run tests

on:
  push:
    branches:
    - test/actions

jobs:
  macOS-tests:
    runs-on: macos-latest
    name: test actions
    steps:
      - uses: feather-framework/feather-actions@0.0.4
  


